{% set name = "readdy" %}
{% set version = "2.0.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: eda816e9500c59372fb17e5bdef7257b5e577b26372ea0ad5eb49ce0b3b9071a

build:
  number: 0
  skip: true  # [win]
  rpaths:
    - lib/
    - lib/readdy_plugins

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - python
    - h5py
    - hdf5
    - zlib
    - spdlog >=1.9.0
    - nlohmann_json
    - pybind11
    - blosc
    - fmt
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - h5py
    - pint
    - tqdm
    - hdf5
    - zlib

test:
  imports:
    - readdy
  requires:
    - nose
  commands:
    - nosetests readdy -s -vv --with-doctest --doctest-options=+NORMALIZE_WHITESPACE,+ELLIPSIS

about:
  home: https://github.com/readdy/readdy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python / C++ based particle reaction-diffusion simulator
  description: |
    ReaDDy (standing for [Rea]ction [D]iffusion [Dy]namics) is a particle based
    reaction-diffusion simulator that can be configured and run with Python 3.6+.
    The Python interface wraps around a C++ implementation for good performance.
    Trajectories are written using the flexible HDF5 format.
  doc_url: https://{{ name }}.github.io/
  dev_url: https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - clonker
    - chrisfroe
