{% set name = "readdy" %}
{% set version = "2.0.12" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e87e6d710941676e5b81fb0d2932601c08adf41da6c7c3aa9ec00f1b927b4eb3

build:
  number: 0
  skip: true  # [win]
  rpaths:
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - conan
    - spdlog 1.10.0
    - nlohmann_json 3.10.3
    - fmt 8.1.1
  host:
    - python
    - h5py
    - hdf5
    - zlib 1.2.*
    - blosc 1.21.1
    - numpy >=1.14
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - h5py
    - pint
    - tqdm
    - hdf5
    - zlib 1.2.*

test:
  imports:
    - readdy
  requires:
    - nose
  commands:
    - nosetests readdy -s -vv --with-doctest --doctest-options=+NORMALIZE_WHITESPACE,+ELLIPSIS

about:
  home: https://github.com/readdy/readdy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python / C++ based particle reaction-diffusion simulator'
  description: |
    ReaDDy (standing for [Rea]ction [D]iffusion [Dy]namics) is a particle based
    reaction-diffusion simulator that can be configured and run with Python 3.6+.
    The Python interface wraps around a C++ implementation for good performance.
    Trajectories are written using the flexible HDF5 format.
  doc_url: https://{{ name }}.github.io/
  dev_url: https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - clonker
    - chrisfroe
