{% set name = "readdy" %}
{% set version = "2.0.13" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3844a462a143389340c892386004db807e38847db9fb2c847194a7f40ce7b409

build:
  number: 3
  skip: true  # [win]
  rpaths:
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - python
    - blosc
    - h5py
    - hdf5
    - fmt
    - nlohmann_json
    - numpy
    - pybind11
    - pybind11-abi
    - spdlog
    - zlib
  run:
    - python
    - h5py
    - pint
    - tqdm
    - hdf5

test:
  imports:
    - readdy
  requires:
    - pytest
  commands:
    - python -m pytest --pyargs readdy.tests -v

about:
  home: https://github.com/readdy/readdy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python / C++ based particle reaction-diffusion simulator'
  description: |
    ReaDDy (standing for [Rea]ction [D]iffusion [Dy]namics) is a particle based
    reaction-diffusion simulator that can be configured and run with Python 3.6+.
    The Python interface wraps around a C++ implementation for good performance.
    Trajectories are written using the flexible HDF5 format.
  doc_url: https://{{ name }}.github.io/
  dev_url: https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - clonker
    - chrisfroe
